name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: summarize-ai-458912

      - name: Build and Push Docker image
        working-directory: ./backend
        run: |
          gcloud builds submit --tag gcr.io/summarize-ai-458912/accessible-portal-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy summarizer-api \
            --image gcr.io/summarize-ai-458912/accessible-portal-backend \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated