name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verify GCP_SA_KEY secret is set
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "GCP_SA_KEY secret is NOT set!"
            exit 1
          else
            echo "GCP_SA_KEY secret is set ✔️"
          fi
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: summarize-ai-458912
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Check gcloud authentication
        run: gcloud auth list
      - name: Build and Push Docker image
        working-directory: ./backend
        run: |
          gcloud builds submit --tag gcr.io/summarize-ai-458912/accessible-portal-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy summarizer-api \
            --image gcr.io/summarize-ai-458912/accessible-portal-backend \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
