name: Deploy to Cloud Run

on:
  push:
    branches:
      - prod
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: summarize-ai-458912

      - name: Build and Push Docker image
        working-directory: ./backend
        run: |
          IMAGE_NAME=gcr.io/summarize-ai-458912/summarizer-api-${{ github.ref_name }}
          gcloud builds submit --tag $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          SERVICE_NAME=summarizer-api
          if [[ "${{ github.ref_name }}" == "staging" ]]; then
            SERVICE_NAME=summarizer-api-staging
          fi
          IMAGE_NAME=gcr.io/summarize-ai-458912/summarizer-api-${{ github.ref_name }}
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
